### ISSUE TITLE
增加 Monaco-editor 功能

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#100]
将 jupyterlab 中 default editor 替换为 monaco

- [x] 使用官方 org 中的 [jupyterlab-monaco](https://github.com/jupyterlab/jupyterlab-monaco) 扩展

- [x] 解决引入问题

- [x] 解决 css 问题

------ 至此可以使用状态 ------

- [x] 解决 console 中的 warning、error

**Comment by lzfxxx** [comment]
- [ ] git submodule 试验

**Comment by lzfxxx** [comment]
下次安装，需要：
1. 删除 jupyterlab-monaco node_modules 中的 @jupyterlab
2. 改 monaco-editor  中 .svg css

**Comment by lzfxxx** [comment]
source-map -U
source-map-support@0.4.3
