### ISSUE TITLE
可以使用shell 命令在notebook内从网络上下载文件到文件系统根目录

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#103]
可以使用shell 命令从网络上下载文件到根目录

## Expected Behaviour

不能对除用户文件夹以外的文件夹有写入删除操作

## Current Behaviour

可以写入
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
安全性問題 ref #154

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#4
