### ISSUE TITLE
1.1 Pre-released testing report

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#108]
testing report 有发现的可能问题，大家各自确认一下。

【链接】0512待修改问题-腾讯文档
https://docs.qq.com/doc/BIheee2prhkR13GiCV0IKflg3l57NH4tSKuF3?ADUIN=491730572&ADSESSION=1526087450&ADTAG=CLIENT.QQ.5561_.0&ADPUBNO=26807&ADUIN=491730572&ADSESSION=1526087450&ADTAG=CLIENT.QQ.5561_.0&ADPUBNO=26807

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
已经修改完成：
4, 5, 6, 7, 8, 9, 13, 15, 16, 18, 23, 25, 27, 31, 32, 34

**Comment by bingweichen** [comment]
已完成 20，21
28 未发现问题

**Comment by bingweichen** [comment]
16 请详细描述

**Comment by lzfxxx** [comment]
待完成 3，36

**Comment by lzfxxx** [comment]
3 完成
36 move to #113

**Comment by Acrobaticat** [comment]
28, 30 skipped
