### ISSUE TITLE
notebook 开启速度优化（包括JupyterLab 镜像大小优化 #21）

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#113]
## Expected Behaviour

去除固定 timeout

## Current Behaviour

第一次打开 notebook，用了固定 timeout 的方式，以保证 notebook 后端启动完成
JupyterLab 镜像大小现在有20G，需要调整一下 Dockerfile ，应该也能帮助缩短启动速度（详情 #21 ）

## Possible Solution

1. 在新建完成项目时，就开始启动 notebook，减少 notebook 开启等待时间
2. 去除固定 timeout，用更好的方法去 check notebook是否启动完成

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
透过前端JS发送状态确认要求，看是否从202->400状态，并等待一段时间后开启并加载。
