### ISSUE TITLE
公开项目变成私有或者删除

### ISSUE THREAD

**Issue by zjn0224** [momodel/mo#115]
## Current Behaviour

项目公开后无法变成私有或者删除。

## Possible Solution

私有化或者删除之后老版本其他用户还可以继续使用

**Comment by lzfxxx** [comment]
项目权限之针对项目的可见性
API的权限是dev 不可见，版本号可见
需要修改:
- [ ] 允许随意修改项目权限
- [ ] 版本发布后仍然可以发布 dev 版

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#27
