### ISSUE TITLE
用户输入错误的 url  的处理

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#118]
当用户输入不存在的url 或 不存在的 project 或者 request 的 id，应该显示一个默认不存在页面，
还是跳转至 对应的 主页面？
## Steps to Reproduce (for bugs)

1.

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/40045857-006dc5c2-585e-11e8-8333-5bd45de83085.png)
 知乎供参考

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/40046307-3c22cd8c-585f-11e8-8952-cbc772b8dede.png)
github供参考

**Comment by zjn0224** [comment]
![404](https://user-images.githubusercontent.com/22392238/40298500-f2059cfa-5d15-11e8-91e5-2ebe83baa883.png)

**Comment by zjn0224** [comment]
![404](https://user-images.githubusercontent.com/22392238/40708955-588b903e-6427-11e8-8805-e685c372516b.png)
