### ISSUE TITLE
Incentives for developers

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#12]
给上传module，app的开发者给与积分奖励，积分可兑换T恤等实物。
防恶意欺诈: 预防恶意上传无效module，app套取实物的行为。

**Comment by lzfxxx** [comment]
This is one of the most important part of a UGC platform, which need more research, discussion and a more complete strategy, i think.

Meanwhile, an app/module/dataset evaluation framework/strategy is also needed. Maybe framework like [danku](https://github.com/algorithmiaio/danku)?

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#5
