### ISSUE TITLE
当用户mouse over消息中心时，如果没有消息，我们应该要怎么处理？

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#121]
## Steps to Reproduce (for bugs)

1.

**Comment by WestonLu** [comment]
![messagebox](https://user-images.githubusercontent.com/24969222/40177205-79058fa2-5a10-11e8-8e2e-b1344da6b859.jpg)

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/40177222-8673ca8c-5a10-11e8-91b2-dab884ce9a8f.png)

**Comment by zjn0224** [comment]
图标大了点，80%大小差不多了
