### ISSUE TITLE
收藏与点赞响应时间过长，有单个js线程需要下载过多数据

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#122]
## Steps to Reproduce (for bugs)

1.

**Comment by WestonLu** [comment]
点赞与收藏后会返回用户的信息，以前用户的头像是base64格式存储在数据库中，所以载入很慢，现在的头像存储方式已经更改，所以没有了此问题。解决办法是删除以前库中存放的base64头像数据。
