### ISSUE TITLE
Jupyter Lab 界面设计修改

### ISSUE THREAD

**Issue by zjn0224** [momodel/mo#126]
## Possible Solution

1.添加当前所在项目的名称
2.调整颜色和间距
3.hint和tips收入help

**Comment by zjn0224** [comment]
![jupyterlab](https://user-images.githubusercontent.com/22392238/40166563-66b64824-59f1-11e8-8ef1-004d2ff99475.png)

**Comment by Acrobaticat** [comment]
3. hint and tips 暂时不考虑加入到help中
Hint 和 tips 调整成左侧字体同样大小，并且对齐
