### ISSUE TITLE
Jupyter Lab tips和hint设计优化

### ISSUE THREAD

**Issue by zjn0224** [momodel/mo#127]
## Possible Solution

TIPS：
1. 增加动效
2. 丰富文案

HINT:
1. 页面增加黑色的蒙版与弹框区分开
2. 左侧切换tab弹框不对应

## Steps to Reproduce (for bugs)

1.

**Comment by zjn0224** [comment]
![page-1-1](https://user-images.githubusercontent.com/22392238/40220438-b01bc916-5aab-11e8-861c-b6f9297d59d0.png)
![page-1-2](https://user-images.githubusercontent.com/22392238/40220439-b0770998-5aab-11e8-8877-7ddf14e9a1f5.png)
![page-1-3](https://user-images.githubusercontent.com/22392238/40220440-b0c0a5da-5aab-11e8-8a91-9e40ff349c8b.png)

**Comment by zjn0224** [comment]
TIPS修改完毕，Hint还没有

**Comment by Acrobaticat** [comment]
讨论后，Hint不调整，保持原样
