### ISSUE TITLE
后端服务debug版rebuild太慢(写了根据环境加载，可关闭)

### ISSUE THREAD

**Issue by bingweichen** [momodel/mo#136]
让近义词包synonyms动态加载（相应api调用时加载），部署环境时需更改到直接加载

- [x] 让近义词包synonyms动态加载（相应api调用时加载）

- [x] 部署环境时需更改到直接加载

## Steps to Reproduce (for bugs)

1.

**Comment by lzfxxx** [comment]
写了根据环境加载，可关闭
