### ISSUE TITLE
建议简化注册的必填项

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#137]
注册要填写的太多了，建议简化
## Steps to Reproduce (for bugs)

1.

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/40213432-ff0b0fd8-5a87-11e8-86ac-8abdcd2ae486.png)

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/40213453-19f322ae-5a88-11e8-8a06-598fad420231.png)

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/40214340-b552dd80-5a8c-11e8-9b56-349de3c2ae87.png)

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#30
