### ISSUE TITLE
Website help documents for four level users

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#14]
Website help documents for four level users

## Steps to Reproduce (for bugs)

1.

**Comment by bingweichen** [comment]
focus on u3, u4. some simple functions interview for u1,u2

**Comment by Acrobaticat** [comment]
Assigned to 潘虹安

**Comment by rehearsal77** [comment]
[https://free.modao.cc/app/MMLygvm8G1L96ZYNBvehbxoBi5jJg2e](url)
app端界面已更新。请UI和开发组参考此原型图的功能与交互设计，有疑问及时沟通，谢谢！
修改功能汇总：
1. 聊天首页中将右侧“分类”按钮更改为“➕”，点击加号显示“发布需求、我的收藏、我的回答”快捷按钮。
2. 输入框上方仅显示根据实时热搜生成的热门应用，不显示其他不同级别信息。
3. 个人中心新增“全部动态”和“我的回答”功能，全部动态包括关注、评论、收藏、点赞、回答问题。
4. 个人中心点击头像进行个人资料修改（由于开发已经完成该模块，所以未重新设计界面）。
5. 个人中心头像下方新增个性签名功能。优先级P1，若实现较为复杂，可放入迭代版本。

**Comment by rehearsal77** [comment]
[https://free.modao.cc/app/MMLygvm8G1L96ZYNBvehbxoBi5jJg2e](url)
app端界面已更新。请UI和开发组参考此原型图，有疑问及时沟通，谢谢！
修改功能：
1. 聊天首页中将右侧“分类”按钮更改为“➕”，点击加号显示“发布需求、我的收藏、我的回答”快捷按钮。
2. 输入框上方仅显示根据实时热搜生成的热门应用，不显示其他不同级别信息。
3. 个人中心新增“全部动态”和“我的回答”功能，全部动态包括关注、评论、收藏、点赞、回答问题。
4. 个人中心头像下方

**Comment by rehearsal77** [comment]
[this](https://free.modao.cc/app/MMLygvm8G1L96ZYNBvehbxoBi5jJg2e)
app端界面已更新。请UI和开发组参考此原型图，有疑问及时沟通，谢谢！
修改功能：
1. 聊天首页中将右侧“分类”按钮更改为“➕”，点击加号显示“发布需求、我的收藏、我的回答”快捷按钮。
2. 输入框上方仅显示根据实时热搜生成的热门应用，不显示其他不同级别信息。
3. 个人中心新增“全部动态”和“我的回答”功能，全部动态包括关注、评论、收藏、点赞、回答问题。
4. 个人中心头像下方

**Comment by Acrobaticat** [comment]
上方關於app端界面調整，已經移至 #43

**Comment by Acrobaticat** [comment]
視頻內容需要放置於外部視頻網站，並且坎入到github.io裡面
