### ISSUE TITLE
SUTD关于MO的建议与Bugs

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#141]
请 @WestonLu @zjn0224 @rehearsal77 将周日与SUTD学生交流后的内容，列在下方统一进行讨论处理。

## Steps to Reproduce (for bugs)

1.

**Comment by WestonLu** [comment]
**建议：**

1. Developer 是否可以 publish code？module和app的开发者可以公开他的代码让其他的开发者查看，甚至fork后进行编辑。
2. 世界频道可以增加link，点击即可跳跃到对应的request或project。
3. 能否多人协作进行项目开发？ （jupyter lab原生支持）

**BUG：**

1. DATASET新建后，clone窗口点击后不消失。
2. GIt clone后push异常
3. 页面缩放后workspace后侧的 overview不能滚动下拉。

**其他：**

1. 网站访问速度慢
2. GPU支持
3. ？？命令查看源代码的安全性问题
4.把component（例如世界频道）做成slack一样的插件

**Comment by zjn0224** [comment]
问题：request 的回答采纳与否不够明显
建议：采纳图标配以文字说明

**Comment by Acrobaticat** [comment]
@rehearsal77 针对上述的问题，分别新增加各项Issues.
