### ISSUE TITLE
『世界频道』『消息通知』『私信/讨论群』『线上问答/回馈机制』的整合设计

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#143]
## Steps to Reproduce (for bugs)

1.

**Comment by zjn0224** [comment]
世界频道和私信、讨论群可以合并，消息通知以及线上问答保留原先的独立入口。

**Comment by zjn0224** [comment]
<img width="379" alt="qq20180522-141154 2x" src="https://user-images.githubusercontent.com/22392238/40346177-90fd54ca-5dce-11e8-98c3-9bbf578bdf83.png">
参考IBM形式

**Comment by rehearsal77** [comment]
![chatting-box](https://user-images.githubusercontent.com/38311567/40533945-e6e30136-6036-11e8-959f-5acb3e4bd527.png)
小莫助手和CEO合并（周一会更新设计稿，将tab放在聊天框上方，点击可切换），好友功能取消，世界频道与消息通知仍然独立。

**Comment by Acrobaticat** [comment]
尽量使用外部消息沟通机制，例如Slack

**Comment by zjn0224** [comment]
![chatting-box copy 2](https://user-images.githubusercontent.com/22392238/40600950-c6d93a76-6285-11e8-90b2-b6244b4bc631.png)
![chatting-box copy](https://user-images.githubusercontent.com/22392238/40600951-c744fc3e-6285-11e8-8b7f-395024b93fa1.png)

**Comment by Acrobaticat** [comment]
先考虑世界频道（利用slack频道）、消息通知

**Comment by zjn0224** [comment]
![Uploading 空 copy.png…]()

**Comment by zjn0224** [comment]
![copy](https://user-images.githubusercontent.com/22392238/40775099-cff510b4-64f9-11e8-8924-c21c6db35337.png)

**Comment by WestonLu** [comment]
正在研究slack的api

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/40818646-c57080b0-658a-11e8-91bd-184664eda1b6.png)

目前的想法是 用户未登录时可以看到世界频道（我们自己设置一个user去拿消息），用户想发消息时，必须登录。  
登录按钮可在世界频道下方？

**Comment by WestonLu** [comment]
用户是否需要slack账号来登录世界频道？（slack需要翻墙）

-   如果用户不需要slack，那我们就后端使用一个账户来发消息，带userID参数并在后端处理后发送到前段
-   如果用户使用slack，那么相当于我们的网站需要登录两个账户...好处是用户可以在slack上同步读到世界频道的内容。

**Comment by WestonLu** [comment]
https://sidecar.gitter.im/

**Comment by Acrobaticat** [comment]
Adapted sidercar.gitter.im.

**Comment by Acrobaticat** [comment]
再另外寻找基于gitter为基础，封装可坎入到前端的聊天介面，必须满足github帐号能够对应我们系统帐号的功能需求。

**Comment by WestonLu** [comment]
搭建一个聊天服务器？https://github.com/RocketChat/Rocket.Chat，前端还是要自己做。
好处是可以有权限删除里面的帖子，避免言论风险。

**Comment by WestonLu** [comment]
创建新用户时，为其在Rocket.Chat的mongo数据库中创建一个同名同密码的账号，在用户登录时，自动为其登录。

**Comment by WestonLu** [comment]
如果为 每个用户创建同样的密码，可以避免用户只登陆聊天站点。
如果聊天密码与mo网站的密码相同，需要写改密码的功能来同步密码。

**Comment by WestonLu** [comment]
需要给世界频道在右侧设计一个隐藏和弹出的按钮。

**Comment by WestonLu** [comment]
- [ ] 新建用户自动创建聊天账号（用户名，密码与主站相同）
- [ ] 用户登录自动登录聊天室（判断是否有账号，如果没有注册账号）
- [ ] 创建官方账号，发送系统消息
- [ ] logo
- [ ] css
- [ ] 欢迎词
- [ ] 研究小莫机器人合并的可行性

**Comment by WestonLu** [comment]
改用slack

- [ ] 注册slack work space
- [ ] 创建 slack app
- [ ] 用户点击加入slack，弹modal引导用户创建slack账号并授权
- [ ] 存储用户的slack token 到数据库
- [ ] 使用用户的slack token发送信息到世界频道
- [ ] 读取世界频道的信息并展示到页面上
- [ ] 建立官方账户并发送官方消息（创建app 发布request等）到slack

**Comment by WestonLu** [comment]
与 slack 的连接不稳定，经常出现
requests.exceptions.ProxyError: HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/channels.history (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))

**Comment by WestonLu** [comment]
https://api.slack.com/events-api
测试 slack event 需要一个接收消息推送的外网 url ，本地测试无法进行

**Comment by WestonLu** [comment]
https://api.slack.com/docs/rate-limits#tier_t4

slack 的api 有调用频率限制，很可能在多人访问我们的网站时因调用太频繁而被限制。

**Comment by WestonLu** [comment]
Feature/API | Limit | Note
-- | -- | --
Posting messages | 1 per second | short bursts >1 allowed
Web API methods | 1-100+ requests per method per workspace per minute | Each method assigned a rate limit tier. All methods support bursting
Incoming webhooks | 1 per second | short bursts >1 allowed
Events API events | 30,000 deliveries per hour per workspace. | Larger bursts are sometimes allowed.
Outgoing webhooks | 1 per second | short bursts >1 allowed

**Comment by WestonLu** [comment]
- [ ] 部署调试，部署时需更改 跳转的 url 设置
- [ ] 部署调试， event api 的 url 测试

**Comment by WestonLu** [comment]
slack不支持 iframe嵌入

**Comment by WestonLu** [comment]
slack 安卓 不翻墙下载不到 app

**Comment by WestonLu** [comment]
slack 的人数限制问题
https://davechen.net/2017/01/slack-user-limit/

more than 12K

**Comment by WestonLu** [comment]
feedback 改为 与客服加入多人聊天，发送消息到此群聊中。

- [ ] 前端及后端更改
- [ ] mo成员加入slack账号，并在后端写如各成员的slack_id
- [ ] 部署调试

**Comment by Acrobaticat** [comment]
ref. #101 #89
