### ISSUE TITLE
代码公开问题

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#147]
module和app的开发者可以公开他的代码让其他的开发者查看，甚至fork后进行编辑
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
1. 在Explore里面，对于每个Project增加一个Tab，显示Project内的档案列表，并且可以浏览内容，同时增加Duplicate Project.
2. 标注 Project的 duplicate对象纪录

**Comment by lzfxxx** [comment]
方案1: 直接写个给文件目录（work dir）的 filebrower

- file server+前端，成本较高
方案2: 自建 git server + web UI
方案3：关联 github + github restful api
- 最简单
- 可以用 github oauth 登录
- 可以拥有有 github 的 code base
- 代码的可见性与公开性也交给了用户
- 25M 大小上限

**Comment by Acrobaticat** [comment]
采用方案2

**Comment by lzfxxx** [comment]
使用 [klaus](https://github.com/jonashaag/klaus) 
唯一能找到的
- 不会太重（重：自己包含认证，用户管理等自成一套网站的功能）
- 能够写扩展支持 ipynb 的预览

**Comment by lzfxxx** [comment]
TODO:

- [ ] repo root 只能设为某个用户的 repo 目录，因此需要做 proxy 转发，或者找到 klaus 的参数去支持
- [ ] ipynb 插件

**Comment by lzfxxx** [comment]
其他 commits 见 [klaus/master](https://github.com/momodel/klaus/commits/master)
