### ISSUE TITLE
世界频道增加link

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#148]
世界频道可以增加link，点击即可跳跃到对应的request或project。
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
related to #143

**Comment by Acrobaticat** [comment]
Slack的解決方案已經完成，但目前因為Slack服務器響應時間太慢，還是先改成使用Rocket Chat的方式

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#32
