### ISSUE TITLE
协同办公机制

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#149]
可以新增协同办公机制，实现多人协作进行项目开发，需确认jupyter lab是否原生支持该功能。
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
目前已知是用Google Drive，共享與共同編輯同一個.ipynb檔案

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#33
