### ISSUE TITLE
management of  messages

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#15]
是否在用户页面增加 message的展示，提供分类浏览与删除功能

**Comment by lzfxxx** [comment]
Simplified GitHub Message center.
Hover display new messages
Click enter message center

**Comment by WestonLu** [comment]
github 的消息展示
![2f3e01e4-6d48-3d50-7c7a-f4a206f8d8b7](https://user-images.githubusercontent.com/24969222/39508215-345f780c-4e14-11e8-8835-2b391f7f944a.jpg)

赵婧楠设计的消息展示

**Comment by Acrobaticat** [comment]
@zjn0224 请协助确认UI设计相关页面

**Comment by Acrobaticat** [comment]
最好用广泛使用的协议，成熟的方案

消息不是拿来通知的，应该是自动化的一个管道，协作/自动化的基础

**Comment by Acrobaticat** [comment]
考虑现有已经在使用的flask-socketio，以及其他如RabbitMQ / RocketMQ / Kafka等相关机制
