### ISSUE TITLE
GIt clone后push异常

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#151]
Dataset GIt clone后push异常
## Possible Solution

理论上`chown -R apache:apache /var/www/user_repos/xxx_repo`可以解决问题

## Steps to Reproduce (for bugs)

1.

**Comment by lzfxxx** [comment]
[git over http](http://blog.xuite.net/zack_pan/blog/65273998-GIT+over+HTTP+%28GIT+HTTP+Transparent%29)
