### ISSUE TITLE
源代码的安全性问题

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#154]
？？命令可以查看源代码，有安全隐患。
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
1. 用戶代碼保護 - 用戶可否取得Module裡面的代碼
2. Mo系統保護 - 我們對於用戶的管控（亦或是提供工具與幫助），主要是透過Client() API的方式，如何保護Client() API的內容保持不揭露（以後可能還有其他的工具）？

**Comment by lzfxxx** [comment]
1. weight 可选是否共享
2. PKI 控制调用
