### ISSUE TITLE
notebook里新建项目报错

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#157]
学生使用notebook里新建launcher时出现403报错。
用户名：zhijun
项目名：test
## Steps to Reproduce (for bugs)

1.

**Comment by rehearsal77** [comment]
![3051527475886_ pic](https://user-images.githubusercontent.com/38311567/40595072-1604e3c8-6265-11e8-9608-de46bcaf832c.jpg)
报错页面提示

**Comment by lzfxxx** [comment]
使用 supervisord 跑后端以后 user_directory 权限问题，改为用 admin 去跑后端
