### ISSUE TITLE
share project or request

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#16]
对外share project 或 request 到微信？微博？qq？
对内share 给 其他用户？

**Comment by lzfxxx** [comment]
Auto generate H5 page, shows the example/prediction interface, with Web API for audio, photo etc.

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#6

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#36
