### ISSUE TITLE
react 中图标方案

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#167]
## Current Behaviour

现在使用的是 antd 的自带图标，以后如果要自定义，可采用 svgr 的方式

## Possible Solution

1. [svgr 可以方便的用 webpack 打包 svg 成为 react 组件，可以调整长宽颜色等属性](https://github.com/smooth-code/svgr)
2. [如使用阿里图标，可以直接用 @font-face 的方式](http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8cf4382a&helptype=code)

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#39
