### ISSUE TITLE
request详情页面优化

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#186]
## Expected Behaviour
1. 新增对需求评论的回复、删除（或举报）功能。所有人可以回复，评论者本人（以及后台管理）可删除，其他用户可举报。
2. 新增对需求回答的删除（或举报）、编辑功能。删除（举报）功能同上。
3. 回答框增加markdown插件，支持markdown编写答案。
4. 关于回答时选择项目的方式待讨论。

**Comment by rehearsal77** [comment]
<img width="474" alt="2" src="https://user-images.githubusercontent.com/38311567/42161632-3be6c9c8-7e2e-11e8-99ea-0eb2b786f02e.png">

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#46
