### ISSUE TITLE
Permission management for apps/modules/datasets

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#19]
### Apps:
- A unique API key will be assigned to each user. The authorisation of apps will apply on API keys.
- Apps can be called only with authorised keys.
### Modules:
- Code of modules are inaccessible for all users, and modules can be only called with API key with permission.
_If this is hard to apply, maybe module can be open to everyone, and we threat them as open source_
### Datasets:
- Set all directories of datasets Read-Only for users inside JupyterLab.

## Current Behaviour

Apps can be called by anyone.
Modules and datasets can be accessed and edited by anyone inside JupyerLab.

## Steps to Reproduce (for bugs)

1.

**Comment by lzfxxx** [comment]
# 权限管理
###  现方案：
将 user 目录以及 modules 目录挂载进 jupyterlab docker 中
可以做的管控有：
	- 挂载为只读
	- 将代码加密

### 动态加载方案：
在用户点击插入 module 或者 dataset 的时候，再去复制需要的目录进 docker
	- - 挂载可以接近于本地文件系统读写速度，复制的话，如果比较大的目录就会比较慢
	- - 这么做的话代码还是公开的
	- + 但是这样可以给用户完整的读写权限
	- + 插入时可以控制权限

### 所以这里分成了两个问题：
1. module 和 dataset 目录的插入方式
	- 挂载
	- 动态复制
2. module 代码是否加密，代码的暴露方式

### 另外
* 如何添加 api key 来进行调用控制
	* 在模板中每个方法头上加一个装饰器，里面进行限制，要求必须用我们的 client 传入 api_key 进行调用
	* 然后在 client 中 api_key 的权限判断
	* 以上，配上代码加密，应该能够实现对 module 调用的控制

### 加密方案
- cython 编译成 .so 文件（该文件只能被反汇编，无法被反编译）
- 必须在 linux 下编译，然后扔进 linux docker 里，并且保证两边 python 版本相同

**Comment by lzfxxx** [comment]
moved next milestone

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#8

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#50
