### ISSUE TITLE
API 调用的代码封装

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#39]
封装对 App 产生的 API 的 request 调用，变成 python 包。
加入 api_key，在这之上做调用的限制
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
1. 用户新建时，给一个rsa的key值
2. 未来key值将作为验证、统计，以及所有需要gen key的时候的一个输入。

**Comment by Acrobaticat** [comment]
1. 改用ed25519 token

**Comment by WestonLu** [comment]
1. user's settings
2. initial cell in new ipynb
