### ISSUE TITLE
App端界面设计(v2)

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#43]
[app端界面原型图](https://free.modao.cc/app/MMLygvm8G1L96ZYNBvehbxoBi5jJg2e)
app端界面已更新。请UI和开发组参考此原型图的功能与交互设计，有疑问及时沟通，谢谢！
修改功能：
1. 聊天首页中将右侧“分类”按钮更改为“➕”，点击加号显示“发布需求、我的收藏、我的回答”快捷按钮。
2. 输入框上方仅显示根据实时搜索或使用频率生成的热门应用，不显示其他不同级别信息。
3. 个人中心新增“全部动态”和“我的回答”功能，全部动态包括关注、评论、收藏、点赞、回答问题。
4. 个人中心点击头像可以对个人资料进行修改（由于此功能开发已完成，所以未进行界面设计）。
5. 个人中心头像下方新增个性签名功能（优先级较低，如开发评估认为实现较复杂，则此功能可以放入迭代版本）。

**Comment by bingweichen** [comment]
个人中心内容展示有些不明确，如果全部要展示，应该分为3大类，我收藏的（app，需求，回答），我点赞的，我自己的（需求，回答）。原型图内容有重叠，需要讨论。

**Comment by bingweichen** [comment]
底部“➕”交互流程和必要性需要讨论一下，如弹出后点击输入框应如何操作

**Comment by zjn0224** [comment]
![14-](https://user-images.githubusercontent.com/22392238/41035660-e61674ee-69bf-11e8-8927-63cfd4f6efef.png)
![18-](https://user-images.githubusercontent.com/22392238/41035662-e727e7be-69bf-11e8-8620-337aec9b0702.png)
![19-](https://user-images.githubusercontent.com/22392238/41035664-e88bee34-69bf-11e8-9d2a-4beb91334390.png)
![21- copy](https://user-images.githubusercontent.com/22392238/41035665-e8f3687a-69bf-11e8-88ee-9bb16997b5d9.png)

**Comment by zjn0224** [comment]
设计稿见钉钉云盘
