### ISSUE TITLE
提升U3用戶使用体验的界面交互設計修改方案

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#47]
## Current Behaviour

對於網站目前最主要的用戶（U3），我們的網站在幫助U3用戶的角度上，仍然有許多的提升空間。
如何調整現有的操作模式與界面，才能更好的服務U3客戶？
我們需要提出方案，在下個階段中實施。

## Steps to Reproduce (for bugs)

1.

**Comment by lzfxxx** [comment]
- [ ] 增加部署 App 报错反馈，以及运行错误反馈（帮助u3测试 App）

**Comment by Acrobaticat** [comment]
延至下个milestone完成
