### ISSUE TITLE
Mo PRD ver 1.0

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#48]
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
moved to next milestone. 预计5/6

**Comment by rehearsal77** [comment]
工作计划中的平台功能部分已更新完成，并同步至one drive。新增更新Page文档需求，预计5.11之前完成。

**Comment by rehearsal77** [comment]
[蓦-产品需求文档0517.pdf](https://github.com/momodel/mo/files/2011392/-.0517.pdf)
PRD结构：蓦平台目标、主要用户对象、体验流程、UC架构图、页面架构图、功能详述（移动端、Web端）
