### ISSUE TITLE
Job  monitoring and controlling for module functions

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#52]
The monitoring for module calling in jupyterlab now is very poor and rough, a richer monitoring can be provided.

## Possible Solution

1. Save runnning status, e.g is_running, *args/**kwargs or func.__name__ etc, to used_module document.
2. Use these information, connect the job with notebook, and display them in Jobs section/tab.
3. A button to terminate, and a area to see the logs or errors.
4.  Notification for running status changing
5. 开始 long job 时，提醒用户完成时会有通知

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
floydhub log / monitor / congiure
状态 / log 为主要内容
通知 vis app or email 之后
现阶段以网站上为主，cmd line tool之后接上去

**Comment by lzfxxx** [comment]
1. 想办法限制他必须使用 client 去运行 module
2. 提供一个 long_run function 去记录 module 或者用户自己写的代码的运行状态
e.g.  用户写一个 def funcA(): 的方法，他只需要将 funcA 以及所需参数，填写进long_run作为输入，并运行，我们即会记录 funcA  的运行状态，并进行控制
3. 用 long_run 或者我们的 client 运行的方法或者 module， 会被记录 log，并且能够被 terminate
4. 开始 long job 时，会提醒用户长运行的开始

**Comment by Acrobaticat** [comment]
for 上述三點：
1 - mildestone mo_1.1_0511 先不做

2, 3 - 
除了功能，需要在Tutorial Project當中加入，並且在[1-3]進階功能介紹.ipynb當中
運行狀態改變，透過網頁前端側邊的彈窗以及email通知用戶
目前僅提供停止功能，並且在Project的Job頁面中可供用戶點擊
在jupyter notebook中左側的running tab中的功能，需要同樣提供在Project 的 Job tab頁面當中

**Comment by Acrobaticat** [comment]
『jupyterlab running tab 中的 job 控制加入』 moved to next stage

**Comment by Acrobaticat** [comment]
jupyterlab running tab 中的 job 控制加入 新开 issue
