### ISSUE TITLE
展示用户上传的头像

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#53]
网页端
- [x] Discovery project card
- [x] user profile
- [x] 世界频道

手机端
~~ - [ ] Discovery project card ~~
- [x] user profile

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
需要更新用户头像存储机制，由BASE64的方式，改为文件档案结构。并且需要更改全系统需要Avatar的地方。

**Comment by Acrobaticat** [comment]
需要延至下个MileStone完成。

**Comment by Acrobaticat** [comment]
related to #58
