### ISSUE TITLE
Deploy procedure optimise

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#54]
## Possible Solution

1. 在部署时加入转换 ipynb->py 的功能，点击后弹到 py editor，让用户编辑部署所需的 py 文件，然后再进行部署
2. 不要让用户手动删部署//work/下所不需要的文件，而是，在部署时，让他们选择所需的文件/文件夹

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
以及删除 shell command
