### ISSUE TITLE
Modules/Datasets List inside notebook functions

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#56]
在 notebook 中的 module 和 dataset 列表中
1. 显示收藏的 module 和 dataset
2. 加 tag 筛选功能

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
or using solr full-text search.

**Comment by lzfxxx** [comment]
暂时先做 显示收藏的 module 和 dataset

**Comment by Acrobaticat** [comment]
Tag先加上去，试试看

**Comment by Acrobaticat** [comment]
已经在Explore做了tag搜寻功能，在jupyter notebook内还没加上
