### ISSUE TITLE
project的example输出为 文件/音频/视频等的时候页面如何展示

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#57]
文件系统？

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
目前输出的格式仅支持JSON格式，可以显示图片，但未支持音频、视频或是文件档案。

**Comment by Acrobaticat** [comment]
ref. IPFS

**Comment by Acrobaticat** [comment]
先将ipfs简单的挂上docker，作为一个文件系统repository使用

**Comment by Acrobaticat** [comment]
1. 用户可以透过提供 /ipfs/<hash> 上传档案
2. Dataset / Module 部署公开之后，可以放置到/ipfs当中，并且提供<hash>给用户

**Comment by Acrobaticat** [comment]
1. 用户上传数据集档案时，可以提供ipfs hash
2. 部署后的dataset / module，放到/ipfs，并且我们平台在内部引用的时候，直接透过ipfs hash 取得档案内容
3. command line tool包装ipfs ，提供部分取得数据集的功能。

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#12
