### ISSUE TITLE
增加部署 App 报错反馈，以及API运行错误反馈

### ISSUE THREAD

**Issue by lzfxxx** [momodel/mo#61]
增加部署 App 报错反馈，以及API运行错误反馈（帮助u3测试 App）

## Possible Solution

- [x] Display error when calling app, help developer to debug/optimise apps
- [ ] A `Report to Author` button can be added when user getting those errors, to help developer
- submit testing data/reproducing data is also an option

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
『Report to Author』需要討論其必要性，或是有沒有其他的方式？
移到下個階段進行。

**Comment by Acrobaticat** [comment]
不需要出现按钮，直接透过消息通知中心，发给作者。
用户端不需要看错误详情

**Comment by lzfxxx** [comment]
暂时只能做消息提醒
等待消息中心(#15)的加入，以及 message 的 body 栏位，可完成报错信息的查看

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#13
