### ISSUE TITLE
新手界面优化

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#64]
<欢迎来到蓦>界面的文案与UI优化
## Expected Behaviour
用更简洁的语言引导第一次进入的用户使用网站

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
@rehearsal77 @zjn0224  确认方案之后，和开发人员协调开发

**Comment by Acrobaticat** [comment]
related to #74 
duplicated
