### ISSUE TITLE
增加comment说明一开始的.ipynb 档案上方init部分的代码内容

### ISSUE THREAD

**Issue by Acrobaticat** [momodel/mo#69]
## Steps to Reproduce (for bugs)

1.

**Comment by bingweichen** [comment]
- [ ] 增加comment说明一开始的.ipynb 档案上方init部分的代码内容

**Comment by bingweichen** [comment]
# Please use current (work) folder to store your data and models
这句应该不要了

```
# Module will be call at our client methond, with the module's address and parameters
# passed as 'conf'. Its result will be assigned to 'result' valuable
# For more details, see our docs https://momodel.github.io/mo/#
import os
import sys
sys.path.append('../')

# Mo model client for run train and predict
from modules import json_parser
from modules import Client
client = Client('fackAPI')
run = client.run
train = client.train
predict = client.predict

# append work_path to head when you want to reference a path inside the working directory
work_path = ''
```

**Comment by Acrobaticat** [comment]
# You can use other public modules via our Client object with module's identifier 
# and parameters.
# For more detailes, please see our online document - https://momodel.github.io/mo/#

import os
import sys

# Define root path
sys.path.append('../')

# Import necessary packages
from modules import json_parser
from modules import Client

# Initialise Client object
client = Client(key='5asdfoasd0fnd0983', project_id='5ae0c6ae0c11f30f76b7060d', 
                user_ID='zhaofengli', 
                project_type='app', source_file_path='Untitled.ipynb')

# Make run/train/predict commnad alias for furthur use
run = client.run
train = client.train
predict = client.predict

# Run a importred module 
# e.g. 
#      conf = json_parser('{"rgb_image":null,"gray_image":null}') 
#      result = run('zhaofengli/new_gender_classifier/0.0.2', conf)
#
# 'conf' is the parameters in dict form for the imported module
# '[user_id]/[imported_module_name]/[version]' is the identifier of the imported module


# Make controller alias for further use
controller = client.controller

# IMPORTANT: Add 'work_path' to the head of every file path in your code.
# e.g.
#      jpgfile = Image.open(work_path + "picture.jpg") 
work_path = './'
