### ISSUE TITLE
新建需求流程优化

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#71]
## Expected Behaviour
用户新建需求时提供下拉菜单选择项目类型（图片、音频、视频、数据、文字），可以添加附件描述，右侧或下方提供填写示例，新建完成提供反馈；用户可以一步步skip。

**Comment by rehearsal77** [comment]
<img width="388" alt="default" src="https://user-images.githubusercontent.com/38311567/40293092-c9f192e6-5d01-11e8-956b-c7923389454e.png">

**Comment by Acrobaticat** [comment]
related to #57 
利用ipfs，先以ipfs当作一个非结构化文档存储的方式处理。

**Comment by Acrobaticat** [comment]
先不考虑音频、视频。

**Comment by Acrobaticat** [comment]
找一个object detection的model 试试

**Comment by Acrobaticat** [comment]
![Uploading 1(1).png…]()
![Uploading 2.png…]()

**Comment by WestonLu** [comment]
能不能修改request的name 和 想要的回答的class？

**Comment by Acrobaticat** [comment]
可以修改NAME，
不能修改CLASS
CLASS只能三选一

**Comment by WestonLu** [comment]
上传附件功能建议等 ipfs 存储确定后，再做

**Comment by WestonLu** [comment]
- [ ] 修改新request的modal
- [ ] 完成修改request的页面
- [ ] 修改request的input 和 output为listField
