### ISSUE TITLE
第一次进入， 顶部帮助页面作为新的页面

### ISSUE THREAD

**Issue by bingweichen** [momodel/mo#74]
## Steps to Reproduce (for bugs)

1.

**Comment by zjn0224** [comment]
![02- 1](https://user-images.githubusercontent.com/22392238/39616435-f439b68e-4fad-11e8-8a3a-bd0622c7357d.png)

**Comment by Acrobaticat** [comment]
已经完成页面的UI设计，目前尚未更新momodel.ai中

**Comment by zjn0224** [comment]
![02-](https://user-images.githubusercontent.com/22392238/39864337-d8aee18c-547b-11e8-8653-bb470ff784d6.png)

**Comment by zjn0224** [comment]
新版设计效果图

**Comment by Acrobaticat** [comment]
move to next milestone

**Comment by zjn0224** [comment]
![landing page](https://user-images.githubusercontent.com/22392238/41076084-60bfcec0-6a42-11e8-83c6-9acf508a89b7.png)
字体微调修改
