### ISSUE TITLE
首页包含header,  request, explore等需要不登录就可以浏览

### ISSUE THREAD

**Issue by bingweichen** [momodel/mo#75]
## Steps to Reproduce (for bugs)

1.

**Comment by WestonLu** [comment]
- [ ] 未登录时 header 不显示workspace栏
- [ ] explore栏未登录可浏览（点赞、评论等功能点击跳转到登陆页）
- [ ] request栏未登陆可浏览（发布新request、评论、回答、创建app等功能点击跳转到登陆页）

**Comment by WestonLu** [comment]
不登陆如何使用聊天机器人？
不登陆如何使用世界聊天频道？

**Comment by Acrobaticat** [comment]
手机不需要做

**Comment by Acrobaticat** [comment]
在未登入的情况下，把网页端的Mo聊天机器人关闭

**Comment by WestonLu** [comment]
- [ ] 在未登入的情况下，把网页端的Mo聊天机器人关闭
