### ISSUE TITLE
使用站点分析，分析流量点击量等 （如百度）

### ISSUE THREAD

**Issue by bingweichen** [momodel/mo#83]
## Steps to Reproduce (for bugs)

1.

**Comment by lzfxxx** [comment]
zhugeio.com

**Comment by Acrobaticat** [comment]
@zjn0224 @rehearsal77 
1. 透過zhugeio.com的線上工具，增加基礎錨點
2. 對於漏斗功能的分析想法

**Comment by zjn0224** [comment]
[埋点统计-05-11.pdf](https://github.com/momodel/mo/files/1994806/-05-11.pdf)

**Comment by rehearsal77** [comment]
[埋点统计-05-14.pdf](https://github.com/momodel/mo/files/1999697/-05-14.pdf) 部署之后埋点更新版本，主要改动：1. 加入URL方便查看事件 2. 将原先埋过部署之后又消失的时间重新命名埋点 3. 新增launchpage的埋点

**Comment by Acrobaticat** [comment]
使用百度

**Comment by Acrobaticat** [comment]
@WestonLu @rehearsal77 交接一下内容

**Comment by Acrobaticat** [comment]
确认一下数据内容，以及确认全网站（包含jupyter lab开启页）都包含在统计范围内

**Comment by WestonLu** [comment]
- [ ] 添加百度统计代码
- [ ] 查看是否能统计到各个子页面

**Comment by WestonLu** [comment]
![image](https://user-images.githubusercontent.com/24969222/42218978-e43fc97a-7efc-11e8-8ad2-26ca24b6f893.png)
尝试使用百度统计，可定义子页面，免费版最多30个子页面

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#16
