### ISSUE TITLE
个人中心profile中查看收藏的module无法实现

### ISSUE THREAD

**Issue by rehearsal77** [momodel/mo#84]
## Expected Behaviour
profile-favorite-project-module 能够查看收藏的module

## Current Behaviour
profile-favorite-project-module 不能够查看收藏的module

## Possible Solution
加loading

## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
开发版本是正常的，需要上传至momodel.ai之后再进行测试
