### ISSUE TITLE
code snippets 组件修改及提供说明

### ISSUE THREAD

**Issue by zjn0224** [momodel/mo#88]
## Possible Solution

1. 提供适当的解释（说明 capture/ restore output  中的output 是一个变量，可以一次存取多个，写在cell中的注释即可）
2. code snippets 从下面的选项中去掉（更换组件，insert output 并不是一个操作，与切换code 和 Markdown模式的那个功能进行对比）

**Comment by zjn0224** [comment]
修改code snippet组件为下拉菜单，原先的文字换成图标
![image](https://user-images.githubusercontent.com/22392238/42203552-b96ad792-7ed1-11e8-8955-599808df97b7.png)

**Comment by lzfxxx** [comment]
@zjn0224 在 jupyterlab 需要手写 dropdown， 尝试了一下太花时间，先用了临时解决办法，有空再搞

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#18
