### ISSUE TITLE
deletion of project and request

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#9]
if a user deleted one of his module, what the apps which use this module would be like? 
if a user deleted one of his app, the service would go offline?
If a project was bind to a request, can user delete this project? 
Or can we just make all public project undeletable?

**Comment by bingweichen** [comment]
public project can not be delete

**Comment by lzfxxx** [comment]
### For project:
- [ ] add removal for git repo when deletion
- [ ] remove delete button for public project

**Comment by lzfxxx** [comment]
### For request:
request with answer cannot be deleted
