### ISSUE TITLE
insert code & import module 代码块在页面底部

### ISSUE THREAD

**Issue by zjn0224** [momodel/mo#97]
## Current Behaviour

新插入的代码块在页面底部，效果不明显且影响操作

## Possible Solution

插入后页面向上滚动至新插入代码块在页面中部

## Steps to Reproduce (for bugs)

1.

**Comment by WestonLu** [comment]
- [ ] 插入代码（3个cell，1 markdown 2 code 3 code）后，激活markdown，并scroll使markdown在view界面最上方。
