### ISSUE TITLE
explore 頁面點擊進入一條具體的project，後退至explore頁面，explore又刷新至第一頁

### ISSUE THREAD

**Issue by WestonLu** [momodel/mo#98]
不僅僅是explore頁面，包括request頁面，profile頁面都是這樣
## Expected Behaviour

後退至explore頁面，應該不會刷新整個explore
## Current Behaviour

刷新整個explore
## Possible Solution

1. 點擊某一個具體的project，在新的標籤頁展示？
2. url加頁面數
## Steps to Reproduce (for bugs)

1.

**Comment by Acrobaticat** [comment]
This issue was moved to Acrobaticat/mo#22
